In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
project_path = "/content/drive/MyDrive/Saama/patient-dropout-event-forecasting/patient-dropout-event-forecasting"

In [ ]:
import pandas as pd

X_train = pd.read_csv(f"{project_path}/Phase1/train_x.csv")
y_train = pd.read_csv(f"{project_path}/Phase1/train_y.csv")

X_test = pd.read_csv(f"{project_path}/Phase1/test_x.csv")
y_test = pd.read_csv(f"{project_path}/Phase1/test_y.csv")

In [ ]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape :", X_test.shape)
print("y_test shape :", y_test.shape)

X_train shape: (3321, 61)
y_train shape: (3321, 3)
X_test shape : (883, 61)
y_test shape : (883, 3)

In [ ]:
X_train.head()

,Unnamed: 0,Active Comparator Arm Number,Behavioral intervention Number,Biological intervention Number,Combination Product intervention Number,Device intervention Number,Diagnostic Test intervention Number,Dietary Supplement intervention Number,Drug intervention Number,Experimental Arm Number,...,smiless,sponsors/lead_sponsor/agency_class,study_design_info/allocation,study_design_info/intervention_model,study_design_info/intervention_model_description,study_design_info/masking,study_design_info/masking_description,study_design_info/masking_num,study_design_info/primary_purpose,study_type
0,NCT02372344,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,...,NaN,Industry,Randomized,Crossover Assignment,NaN,None (Open Label),NaN,0.0,Basic Science,Interventional
1,NCT05093530,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,...,NaN,Industry,Randomized,Parallel Assignment,"Randomized, double-blind, placebo-controlled t...","Double (Participant, Investigator)",NaN,2.0,Treatment,Interventional
2,NCT02242045,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,['[H][C@@](CC)(NC1=NC=NC2=C1N=CN2)C1=NC2=CC=CC...,Industry,NaN,Single Group Assignment,NaN,None (Open Label),NaN,0.0,Treatment,Interventional
3,NCT01220999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,...,NaN,Other,Non-Randomized,Parallel Assignment,NaN,None (Open Label),NaN,0.0,Treatment,Interventional
4,NCT01007032,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,Industry,NaN,Sequential Assignment,NaN,None (Open Label),NaN,0.0,Treatment,Interventional

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3321 entries, 0 to 3320
Data columns (total 61 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Unnamed: 0                                        3321 non-null   object
 1   Active Comparator Arm Number                      3303 non-null   float64
 2   Behavioral intervention Number                    3321 non-null   float64
 3   Biological intervention Number                    3321 non-null   float64
 4   Combination Product intervention Number           3321 non-null   float64
 5   Device intervention Number                        3321 non-null   float64
 6   Diagnostic Test intervention Number               3321 non-null   float64
 7   Dietary Supplement intervention Number            3321 non-null   float64
 8   Drug intervention Number                          3321 non-null   float64
 9   Experimental Arm Number                           3303 non-null   float64
 10  Genetic intervention Number                       3321 non-null   float64
 11  MaskingType-Care Provider                         3319 non-null   float64
 12  MaskingType-Investigator                          3319 non-null   float64
 13  MaskingType-Outcomes Assessor                     3319 non-null   float64
 14  MaskingType-Participant                           3319 non-null   float64
 15  No Intervention Arm Number                        3303 non-null   float64
 16  Other Arm Number                                  3303 non-null   float64
 17  Other intervention Number                         3321 non-null   float64
 18  Placebo Comparator Arm Number                     3303 non-null   float64
 19  Procedure intervention Number                     3321 non-null   float64
 20  Radiation intervention Number                     3321 non-null   float64
 21  Sham Comparator Arm Number                        3303 non-null   float64
 22  brief_summary/textblock                           3321 non-null   object
 23  brief_title                                       3321 non-null   object
 24  condition                                         3321 non-null   object
 25  condition_browse/mesh_term                        2209 non-null   object
 26  eligibility/criteria/textblock                    3321 non-null   object
 27  eligibility/gender                                3321 non-null   object
 28  eligibility/healthy_volunteers                    3321 non-null   object
 29  eligibility/maximum_age                           2230 non-null   object
 30  eligibility/minimum_age                           3287 non-null   object
 31  enrollment                                        3321 non-null   float64
 32  has_expanded_access                               3291 non-null   object
 33  icdcode                                           2858 non-null   object
 34  intervention/description                          3074 non-null   object
 35  intervention/intervention_name                    3321 non-null   object
 36  intervention_browse/mesh_term                     2120 non-null   object
 37  ipd_info_type-Analytic Code                       199 non-null    float64
 38  ipd_info_type-Clinical Study Report (CSR)         199 non-null    float64
 39  ipd_info_type-Informed Consent Form (ICF)         199 non-null    float64
 40  ipd_info_type-Statistical Analysis Plan (SAP)     199 non-null    float64
 41  ipd_info_type-Study Protocol                      199 non-null    float64
 42  keyword                                           1896 non-null   object
 43  location/facility/address/city                    3001 non-null   object
 44  number_of_arms                                    3303 non-null   float64
 45  oversight_info/has_dmc                            2829 non-null   object
 46  oversight_info/is_fda_regulated_device            1146 non-null   object
 47  oversight_info/is_fda_regulated_drug              1153 non-null   object
 48  patient_data/sharing_ipd                          1187 non-null   object
 49  phase                                             3321 non-null   object
 50  responsible_party/responsible_party_type          3109 non-null   object
 51  smiless                                           1642 non-null   object
 52  sponsors/lead_sponsor/agency_class                3321 non-null   object
 53  study_design_info/allocation                      2593 non-null   object
 54  study_design_info/intervention_model              3287 non-null   object
 55  study_design_info/intervention_model_description  253 non-null    object
 56  study_design_info/masking                         3319 non-null   object
 57  study_design_info/masking_description             129 non-null    object
 58  study_design_info/masking_num                     3319 non-null   float64
 59  study_design_info/primary_purpose                 3115 non-null   object
 60  study_type                                        3321 non-null   object
dtypes: float64(29), object(32)
memory usage: 1.5+ MB

In [ ]:
y_train.head()

    Unnamed: 0  droupout_rate  Y/N
0  NCT02372344       0.000000    0
1  NCT05093530       0.016667    1
2  NCT02242045       1.000000    1
3  NCT01220999       0.052632    1
4  NCT01007032       0.142857    1

In [ ]:
y_train.columns

Index(['Unnamed: 0', 'droupout_rate', 'Y/N'], dtype='object')

In [ ]:
y_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3321 entries, 0 to 3320
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     3321 non-null   object
 1   droupout_rate  3321 non-null   float64
 2   Y/N            3321 non-null   int64
dtypes: float64(1), int64(1), object(1)
memory usage: 78.0+ KB

In [ ]:
missing = X_train.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
missing

study_design_info/masking_description               3192
ipd_info_type-Study Protocol                        3122
ipd_info_type-Informed Consent Form (ICF)           3122
ipd_info_type-Statistical Analysis Plan (SAP)       3122
ipd_info_type-Clinical Study Report (CSR)           3122
ipd_info_type-Analytic Code                         3122
study_design_info/intervention_model_description    3068
oversight_info/is_fda_regulated_device              2175
oversight_info/is_fda_regulated_drug                2168
patient_data/sharing_ipd                            2134
smiless                                             1679
keyword                                             1425
intervention_browse/mesh_term                       1201
condition_browse/mesh_term                          1112
eligibility/maximum_age                             1091
study_design_info/allocation                         728
oversight_info/has_dmc                               492
icdcode                                              463
location/facility/address/city                       320
intervention/description                             247
responsible_party/responsible_party_type             212
study_design_info/primary_purpose                    206
study_design_info/intervention_model                  34
eligibility/minimum_age                               34
has_expanded_access                                   30
Placebo Comparator Arm Number                         18
Experimental Arm Number                               18
Active Comparator Arm Number                          18
Other Arm Number                                      18
No Intervention Arm Number                            18
Sham Comparator Arm Number                            18
number_of_arms                                        18
MaskingType-Investigator                               2
MaskingType-Care Provider                              2
MaskingType-Participant                                2
MaskingType-Outcomes Assessor                          2
study_design_info/masking                              2
study_design_info/masking_num                          2
dtype: int64

In [ ]:
X_train.dtypes.value_counts()

object     32
float64    29
Name: count, dtype: int64

In [ ]:
X_train.duplicated().sum()

np.int64(0)

In [ ]:
missing_percentage = (X_train.isnull().sum() / len(X_train)) * 100

missing_percentage = (
    missing_percentage[missing_percentage > 0]
    .sort_values(ascending=False)
)

missing_percentage

study_design_info/masking_description               96.115628
ipd_info_type-Study Protocol                        94.007829
ipd_info_type-Informed Consent Form (ICF)           94.007829
ipd_info_type-Statistical Analysis Plan (SAP)       94.007829
ipd_info_type-Clinical Study Report (CSR)           94.007829
ipd_info_type-Analytic Code                         94.007829
study_design_info/intervention_model_description    92.381813
oversight_info/is_fda_regulated_device              65.492322
oversight_info/is_fda_regulated_drug                65.281542
patient_data/sharing_ipd                            64.257754
smiless                                             50.557061
keyword                                             42.908762
intervention_browse/mesh_term                       36.163806
condition_browse/mesh_term                          33.483890
eligibility/maximum_age                             32.851551
study_design_info/allocation                        21.921108
oversight_info/has_dmc                              14.814815
icdcode                                             13.941584
location/facility/address/city                       9.635652
intervention/description                             7.437519
responsible_party/responsible_party_type             6.383619
study_design_info/primary_purpose                    6.202951
study_design_info/intervention_model                 1.023788
eligibility/minimum_age                              1.023788
has_expanded_access                                  0.903342
Placebo Comparator Arm Number                        0.542005
Experimental Arm Number                              0.542005
Active Comparator Arm Number                         0.542005
Other Arm Number                                     0.542005
No Intervention Arm Number                           0.542005
Sham Comparator Arm Number                           0.542005
number_of_arms                                       0.542005
MaskingType-Investigator                             0.060223
MaskingType-Care Provider                            0.060223
MaskingType-Participant                              0.060223
MaskingType-Outcomes Assessor                        0.060223
study_design_info/masking                            0.060223
study_design_info/masking_num                        0.060223
dtype: float64

In [ ]:
X_train = X_train.drop(columns=["Unnamed: 0"])
X_test = X_test.drop(columns=["Unnamed: 0"])

y_train = y_train.drop(columns=["Unnamed: 0"])
y_test = y_test.drop(columns=["Unnamed: 0"])

In [ ]:
threshold = 90

cols_to_drop = missing_percentage[missing_percentage > threshold].index

X_train = X_train.drop(columns=cols_to_drop)
X_test = X_test.drop(columns=cols_to_drop)

print(cols_to_drop)

Index(['study_design_info/masking_description', 'ipd_info_type-Study Protocol',
       'ipd_info_type-Informed Consent Form (ICF)',
       'ipd_info_type-Statistical Analysis Plan (SAP)',
       'ipd_info_type-Clinical Study Report (CSR)',
       'ipd_info_type-Analytic Code',
       'study_design_info/intervention_model_description'],
      dtype='object')

In [ ]:
num_cols = X_train.select_dtypes(include=["float64","int64"]).columns

cat_cols = X_train.select_dtypes(include=["object"]).columns

print("Numeric:", len(num_cols))
print("Categorical:", len(cat_cols))

Numeric: 24
Categorical: 29

In [ ]:
print(y_train.columns)

Index(['droupout_rate', 'Y/N'], dtype='object')

In [ ]:
y_train.head()

   droupout_rate  Y/N
0       0.000000    0
1       0.016667    1
2       1.000000    1
3       0.052632    1
4       0.142857    1

In [ ]:
print(y_train.columns)

Index(['droupout_rate', 'Y/N'], dtype='object')

In [ ]:

print(repr(y_train.columns[0]))

'droupout_rate'

In [ ]:

print(y_train.iloc[:5])

   droupout_rate  Y/N
0       0.000000    0
1       0.016667    1
2       1.000000    1
3       0.052632    1
4       0.142857    1

In [ ]:
y_train.loc[:, "droupout_rate"].describe()

count    3321.000000
mean        0.180325
std         0.312551
min         0.000000
25%         0.000000
50%         0.030952
75%         0.166667
max         1.000000
Name: droupout_rate, dtype: float64

In [ ]:
y_train.rename(columns={"droupout_rate": "dropout_rate"}, inplace=True)
y_test.rename(columns={"droupout_rate": "dropout_rate"}, inplace=True)